INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('c2d90c59-b', 2199.2, 'PayPal', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('d0ccc9cc-8', 8972.58, 'Credit Card', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('65a10d6e-2', 1762.98, 'Cryptocurrency', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('19043c24-e', 810.29, 'PayPal', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('b5c3cd9e-6', 6006.59, 'Credit Card', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('294da252-f', 1740.73, 'Bank Transfer', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('ac0f8dac-d', 5005.58, 'Credit Card', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('6c155b49-5', 8068.53, 'PayPal', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('49a4bcc5-0', 1746.95, 'Cryptocurrency', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('58643484-c', 3928.84, 'PayPal', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('12224b96-f', 4083.09, 'PayPal', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('d6bef5b7-d', 1486.7, 'PayPal', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('d6610e9c-7', 6399.38, 'Cryptocurrency', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('7b8573d5-d', 3977.15, 'Cryptocurrency', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('d22fb407-f', 2404.26, 'Cryptocurrency', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('eed4cb16-0', 9616.39, 'Bank Transfer', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('bd1cdb87-0', 4384.13, 'Bank Transfer', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('315511b3-9', 3108.61, 'Credit Card', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('a079b465-c', 7578.39, 'PayPal', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('6faf09af-0', 9152.1, 'Credit Card', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('41b964d1-8', 7100.69, 'Cryptocurrency', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('1c315b2d-6', 10089.76, 'Cryptocurrency', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('13d14bc2-6', 3041.57, 'Bank Transfer', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('fcb8b63b-5', 5088.97, 'Cryptocurrency', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('a646d66c-8', 7211.78, 'Cryptocurrency', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('35bbbcb2-3', 2525.8, 'Bank Transfer', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('b1ef8605-4', 3493.56, 'PayPal', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('c370767f-7', 2522.02, 'Credit Card', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('9da1dfb1-2', 7016.35, 'Bank Transfer', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('6f0d3df2-2', 1328.71, 'Credit Card', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('eb4b2098-0', 6652.85, 'PayPal', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('0bbfb614-2', 3108.24, 'Credit Card', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('9bb8f9b6-8', 7456.05, 'Credit Card', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('8d15537b-8', 3052.25, 'Bank Transfer', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('88811d09-d', 2295.51, 'Cryptocurrency', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('720e3434-7', 3939.34, 'Bank Transfer', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('546f62ec-b', 6493.3, 'Cryptocurrency', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('da95bfa4-a', 8043.38, 'Bank Transfer', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('af26adad-a', 6273.64, 'Credit Card', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('4fb6a20f-b', 1124.8, 'Credit Card', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('44af74b5-0', 4526.62, 'Cryptocurrency', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('1787ec9b-9', 1691.28, 'Cryptocurrency', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('e533e95d-e', 7381.25, 'PayPal', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('6b9ff4e4-0', 554.35, 'Bank Transfer', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('0aeeda68-f', 2899.6, 'Bank Transfer', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('9734d686-4', 3726.66, 'PayPal', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('e8a309fe-6', 7075.57, 'Credit Card', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('be39a103-5', 2368.13, 'Credit Card', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('2fe4146e-9', 1174.99, 'Cryptocurrency', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('6ed614bc-2', 1142.92, 'Cryptocurrency', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('ddb33966-4', 4398.61, 'PayPal', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('65ff84c6-0', 6894.68, 'Bank Transfer', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('706fd76c-3', 7492.47, 'PayPal', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('7c3905f1-c', 7276.25, 'PayPal', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('fd70967e-6', 1981.54, 'Credit Card', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('33232c94-7', 6840.94, 'Credit Card', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('69b0c1c5-8', 4628.27, 'Bank Transfer', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('220c25ee-7', 4070.4, 'Bank Transfer', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('a5873600-7', 6363.86, 'PayPal', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('d453bbde-4', 2569.98, 'PayPal', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('530f23e5-4', 4939.19, 'Credit Card', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('977f3fea-9', 1979.81, 'Credit Card', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('adacbe8a-8', 5537.27, 'Cryptocurrency', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('ac530431-a', 10673.31, 'Cryptocurrency', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('aab4c866-4', 4421.38, 'Cryptocurrency', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('4b271b2e-8', 7678.55, 'Bank Transfer', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('ab8b15ab-f', 3160.94, 'PayPal', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('c17db19e-7', 7996.35, 'Cryptocurrency', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('a4fe7640-6', 9374.12, 'PayPal', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('6df8796d-7', 2377.45, 'PayPal', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('44507e27-d', 5720.46, 'Credit Card', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('71f4d5cb-d', 5267.53, 'PayPal', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('32fef809-3', 5309.06, 'Cryptocurrency', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('48286990-f', 1741.01, 'Credit Card', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('d080c310-7', 5353.3, 'Bank Transfer', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('aab9b2a6-0', 6904.17, 'Bank Transfer', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('662502a9-6', 8155.32, 'Credit Card', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('4d68baf9-7', 3903.12, 'PayPal', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('2391f572-4', 1904.11, 'Cryptocurrency', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('8243a910-0', 2571.09, 'Cryptocurrency', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('6b9b3a26-a', 1353.12, 'Cryptocurrency', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('c906b8eb-0', 5153.78, 'Cryptocurrency', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('d1838db2-f', 3196.68, 'Cryptocurrency', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('3d017457-0', 3609.52, 'Credit Card', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('ea5b98fd-2', 5385.91, 'PayPal', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('2475375a-1', 2009.98, 'Bank Transfer', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('e8e7ed65-8', 5477.52, 'Bank Transfer', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('bea99f84-6', 1642.25, 'Bank Transfer', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('bb0f88ca-2', 1630.62, 'Bank Transfer', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('a010195d-0', 3685.24, 'Cryptocurrency', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('71d8284a-8', 2428.43, 'Bank Transfer', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('cb903233-4', 1494.93, 'Bank Transfer', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('73896df6-4', 5100.24, 'Credit Card', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('e4a7d739-5', 5020.5, 'PayPal', 'completed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('fb911417-8', 3885.14, 'Bank Transfer', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('8e8af280-a', 8104.05, 'Cryptocurrency', 'failed');
INSERT INTO payments (contract_id, amount, payment_method, status) VALUES ('cdca0f03-c', 5953.97, 'Cryptocurrency', 'completed');