INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('85d3d266-8', '7d1ec63d-4', 'Great job, met expectations well.', 4);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('5ab8682f-f', 'dae484c6-6', 'Exceptional work! Highly recommended.', 5);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('5ab8682f-f', 'ee11d252-1', 'Exceptional work! Highly recommended.', 5);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('5ab8682f-f', 'bb95abb6-c', 'Decent work, but could be improved.', 3);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('33a852b0-2', '465c16dc-3', 'Great job, met expectations well.', 4);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('33a852b0-2', '032f21fa-6', 'Exceptional work! Highly recommended.', 5);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('33a852b0-2', '29644934-8', 'Great job, met expectations well.', 4);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('33a852b0-2', '0298778a-c', 'Exceptional work! Highly recommended.', 5);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('ec98e132-3', 'a54a7813-0', 'Very disappointing, would not recommend.', 1);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('ec98e132-3', 'e0ee0945-0', 'Exceptional work! Highly recommended.', 5);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('64ef70fd-9', '8bd4ece8-3', 'Very disappointing, would not recommend.', 1);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('64ef70fd-9', '60142e4e-e', 'Very disappointing, would not recommend.', 1);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('64ef70fd-9', 'a1182307-e', 'Very disappointing, would not recommend.', 1);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('64ef70fd-9', '62f3bf24-9', 'Not fully satisfied, several issues.', 2);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('64ef70fd-9', '3541aa24-9', 'Exceptional work! Highly recommended.', 5);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('64ef70fd-9', '744500ff-f', 'Great job, met expectations well.', 4);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('00dfcc73-8', 'f26af625-1', 'Very disappointing, would not recommend.', 1);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('8d3ea35c-5', 'b5cb1f48-7', 'Not fully satisfied, several issues.', 2);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('8d3ea35c-5', 'd04eeecd-a', 'Decent work, but could be improved.', 3);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('47b7b97c-e', '804c1256-4', 'Decent work, but could be improved.', 3);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('a28733c4-a', 'b0b97605-b', 'Not fully satisfied, several issues.', 2);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('a28733c4-a', '17a54b9b-7', 'Great job, met expectations well.', 4);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('a28733c4-a', '4da32970-d', 'Exceptional work! Highly recommended.', 5);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('a28733c4-a', '98042a50-7', 'Decent work, but could be improved.', 3);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('7bd9fdb8-5', '8bd4ece8-3', 'Decent work, but could be improved.', 3);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('7bd9fdb8-5', '7a0abb7b-d', 'Not fully satisfied, several issues.', 2);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('ab7a827b-2', '55cfdee2-1', 'Great job, met expectations well.', 4);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('84897cf8-a', '804c1256-4', 'Not fully satisfied, several issues.', 2);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('84897cf8-a', 'eb406f71-c', 'Very disappointing, would not recommend.', 1);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('1e6a5017-3', 'fef0d132-1', 'Very disappointing, would not recommend.', 1);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('afd8ada5-d', '4b5a5164-a', 'Decent work, but could be improved.', 3);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('afd8ada5-d', 'd04eeecd-a', 'Very disappointing, would not recommend.', 1);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('dee61fc3-7', 'f26af625-1', 'Exceptional work! Highly recommended.', 5);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('dee61fc3-7', 'd5cf7f46-d', 'Not fully satisfied, several issues.', 2);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('21b435e6-0', 'adacf265-b', 'Exceptional work! Highly recommended.', 5);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('21b435e6-0', 'eb406f71-c', 'Great job, met expectations well.', 4);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('21b435e6-0', 'a115717e-1', 'Decent work, but could be improved.', 3);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('bb6d8453-b', '8e31e4e6-c', 'Not fully satisfied, several issues.', 2);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('fc3fbba4-1', 'bdb70612-9', 'Very disappointing, would not recommend.', 1);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('25c430d4-a', '5989dae6-c', 'Great job, met expectations well.', 4);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('25c430d4-a', '71bc5f96-3', 'Exceptional work! Highly recommended.', 5);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('25c430d4-a', 'b0b97605-b', 'Great job, met expectations well.', 4);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('25c430d4-a', '55cfdee2-1', 'Great job, met expectations well.', 4);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('24cd2824-5', 'bd7e4ec1-1', 'Great job, met expectations well.', 4);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('76674b43-f', 'adacf265-b', 'Exceptional work! Highly recommended.', 5);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('76674b43-f', 'f9f19dae-c', 'Great job, met expectations well.', 4);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('fa09c8b1-0', '0a96538c-7', 'Exceptional work! Highly recommended.', 5);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('fa09c8b1-0', '804c1256-4', 'Decent work, but could be improved.', 3);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('2b7138a5-e', 'b0b97605-b', 'Exceptional work! Highly recommended.', 5);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('2b7138a5-e', '032f21fa-6', 'Not fully satisfied, several issues.', 2);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('2b7138a5-e', 'cb4ea407-6', 'Decent work, but could be improved.', 3);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('8c19b84e-9', 'd5cf7f46-d', 'Exceptional work! Highly recommended.', 5);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('e479845f-2', '303ea92f-8', 'Not fully satisfied, several issues.', 2);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('e479845f-2', 'f046039f-8', 'Not fully satisfied, several issues.', 2);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('6ae7a76c-6', 'bdb70612-9', 'Not fully satisfied, several issues.', 2);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('6ae7a76c-6', '804c1256-4', 'Great job, met expectations well.', 4);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('6ae7a76c-6', '3478855c-f', 'Decent work, but could be improved.', 3);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('d6668e4d-8', 'df258868-6', 'Great job, met expectations well.', 4);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('7da4c7a9-7', '52ffc6c7-1', 'Exceptional work! Highly recommended.', 5);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('7da4c7a9-7', 'e4c47d8a-b', 'Very disappointing, would not recommend.', 1);
INSERT INTO reviews (reviewer_id, reviewee_id, review_text, rating) VALUES ('7da4c7a9-7', '8c69a0d3-d', 'Decent work, but could be improved.', 3);